### ISSUE TITLE
Add 'wait_for_shutdown' lifecycle hook 

### ISSUE THREAD

**Issue by mabouels** [FireXStuff/firex-flame#2]
Add 'wait_for_shutdown' lifecycle hook to avoid losing task data on --sync when tests shutdown aggressively.

Currently, we might end up with incomplete task data because flame can get killed while writing the data.

**Comment by djungic** [comment]
Waiting for tracking services before releasing the console was added in firexapp, allowing Flame's launcher to wait for model dump completion on sync.
